### PR TITLE
Added the About page (about.html and style_about.css)

### PR DESCRIPTION
**Pull request by ashleyvj**
About page

### CODE REVIEW

**Comment by ashikmeerankutty** [comment]
Add contents of style_about.css to style.css

**Comment by ashikmeerankutty** [comment]
Add contents of style_about.css to style.css

**Comment by abhijithvijayan** [comment]
👍

**Comment by abhijithvijayan** [comment]
keep the repo upto-date and request for a new PR

**Comment by abhijithvijayan** [comment]
Check out this Gist https://kutt.it/tFixcu

**Pull request closed without merging**
