### PR TITLE
Added Preloader + Animated Logo

### PR DESCRIPTION
**Pull request by abhijithvijayan**
*Shows a spinner before loading the page fully

### CODE REVIEW

**Comment by abhijithvijayan** [comment]
It is so fast now as the page elements are quite few and loading is so fast

**Comment by jobinrjohnson** [comment]
The preloader is not visible. Also there are errors in javascript. 

screen shot 2018-01-16 at 6 28 48 am

**Comment by abhijithvijayan** [comment]
I don't think so
I'll check on to that

**Comment by abhijithvijayan** [comment]
added the hover effect on trace logo

**Pull request merged**
